global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'demo-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['app:3000']
